name: reprecinct
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  get: ^4.3.8
  dio: ^4.0.0

  flutter_svg: ^0.23.0+1
  easy_localization: ^3.0.0
  lazy_load_scrollview: ^1.3.0
  intl: ^0.17.0

  shared_preferences: ^2.0.15

  connectivity_plus: ^2.0.3
  webview_flutter: ^2.1.1
  google_fonts: ^2.1.0

  cached_network_image: ^3.1.1
  flutter_easyloading: ^3.0.3
  flutter_html: ^2.2.1
  autocomplete_textfield: ^2.0.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  flutter_typeahead: ^4.1.1
  table_calendar: ^3.0.8
  intl_phone_field: ^3.1.0
  carousel_slider: ^4.1.1
  url_launcher: ^6.1.0
  group_button: ^5.2.2
  flutter_staggered_grid_view: ^0.4.0
  shimmer: ^2.0.0
  country_code_picker: ^2.0.2
  permission_handler: ^10.0.0

  #flutter_launcher_icons: ^0.9.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner: ^2.1.5
  flutter_gen_runner: ^3.0.2

  #  shimmer: ^2.0.0
  flutter_native_splash: ^1.3.2

  flutter_launcher_icons: ^0.9.2



flutter_native_splash:
  color: "#071b5d"
  image: assets/logos/logo.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/appicon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/locales/
    - assets/logos/


